

name: music-box
on:
  schedule:
    - cron: '0 * * * *'  # hourly
  push:
    branches: master
jobs:
  musicbox:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: npm install
     - name: Keepalive Workflow
       uses: gautamkrishnar/keepalive-workflow@2.0.9
       # This workflow has been disabled by GitHub for violating terms of service — https://github.com/gautamkrishnar/keepalive-workflow
       # If you need to raise it from the grave for a personal project, see here: https://web.archive.org/web/20250000000000*/https://github.com/gautamkrishnar/keepalive-workflow
     - name: Update
       uses: ./
       env:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LFMUSERNAME: ${{ secrets.LFMUSERNAME }}
          GIST_ID: ${{ secrets.GIST_ID }}
