

name: music-box
on:
  schedule:
    - cron: '0 * * * *'  # hourly
  workflow_dispatch: {}
  repository_dispatch:
    types: [music-box-keepalive]
  push:
    branches: master
jobs:
  musicbox:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v4
       with:
         node-version: 20
         cache: npm
     - run: npm ci
     - name: Update
       uses: ./
       env:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LFMUSERNAME: ${{ secrets.LFMUSERNAME }}
          GIST_ID: ${{ secrets.GIST_ID }}
